"""Payment gateway integration for /product buy.

Wraps ramashop.my.id, https://ramashop.my.id/docs.html.

RamaShop identifies a paid QRIS deposit by matching the TRANSFERRED
AMOUNT against incoming QRIS history, not by a merchant-chosen
transaction ID -- so every deposit gets a small "unique code" added to
the product price (e.g. Rp1.000 becomes Rp1.073) to make each pending
deposit's expected amount distinguishable from every other one open at
the same time. The unique code is generated by RamaShop itself in the
Create Deposit response (totalAmount), not by us -- callers must always
show totalAmount to the buyer, never the bare product price, or the
buyer will underpay and the deposit will sit pending forever.

confirm_payment() below never trusts a webhook body by itself (RamaShop
has none anyway); it always re-queries the provider's own Check Status
endpoint first.

Env vars required:
    RAMASHOP_API_KEY -- API key from the RamaShop dashboard's API Key menu,
                        sent as the X-API-Key header on every request.

RamaShop has no withdraw endpoint at all (balance can only be checked,
not pulled out via API) -- withdrawals for this account are handled
manually through the RamaShop dashboard, outside this bot.
"""
import json
import os
import time

import aiohttp

from utils.firebase import db

RAMASHOP_BASE = 'https://ramashop.my.id/api/public'
RAMASHOP_API_KEY = os.getenv('RAMASHOP_API_KEY')

ORDER_EXPIRY_MS = 30 * 60 * 1000

# aiohttp's default User-Agent ("Python/3.x aiohttp/x.x") reads as a raw
# HTTP library rather than a real client, which is the kind of signal
# that can trip an anti-bot check in front of a small API (RamaShop
# served an HTML "Bot Verification" challenge instead of JSON in testing,
# on an otherwise valid, correctly-authenticated request). A generic
# browser-like UA avoids that specific tell without pretending to be any
# particular browser/version.
_USER_AGENT = 'Mozilla/5.0 (compatible; MidasBot/1.0; +https://github.com/honerableity/midas-i-python)'


class PaymentGatewayError(Exception):
    """Raised on any non-2xx / malformed response from a gateway."""


def _now_ms():
    return int(time.time() * 1000)


def pakasir_configured() -> bool:
    """Name kept for compatibility with commands/product.py and
    utils/webhook_server.py -- despite the name, this now reports whether
    the active gateway (RamaShop) is configured.
    """
    return bool(RAMASHOP_API_KEY)


def _get_headers() -> dict:
    # No Content-Type here -- this is used for GET requests (/balance,
    # /deposit/status) which carry no body. Sending Content-Type on a
    # bodyless GET is exactly the kind of "not how a real client behaves"
    # signal that triggered RamaShop's anti-bot "Bot Verification" page in
    # testing, even though the request was otherwise valid and correctly
    # authenticated -- a plain curl with just X-API-Key went through fine.
    return {'X-API-Key': RAMASHOP_API_KEY or '', 'User-Agent': _USER_AGENT}


def _post_headers() -> dict:
    # POST /deposit/create sends a JSON body, so Content-Type belongs here.
    return {'Content-Type': 'application/json', 'X-API-Key': RAMASHOP_API_KEY or '', 'User-Agent': _USER_AGENT}


async def get_account_balance() -> int:
    """GET /balance -- a single API-key call, no login step needed (unlike
    the old tokoshopp integration). Used by /payment balance. Never
    cached since balance changes constantly.
    """
    if not pakasir_configured():
        raise PaymentGatewayError('RAMASHOP_API_KEY not configured.')

    url = f'{RAMASHOP_BASE}/balance'
    async with aiohttp.ClientSession() as session:
        async with session.get(url, headers=_get_headers()) as resp:
            raw = await resp.text()
            try:
                data = json.loads(raw) if raw.strip() else {}
            except json.JSONDecodeError:
                raise PaymentGatewayError(
                    f'RamaShop balance check returned a non-JSON response ({resp.status}): {raw[:300]!r}'
                )
            if resp.status != 200 or not data.get('success'):
                raise PaymentGatewayError(f'RamaShop balance check failed ({resp.status}): {data}')
            return int(data.get('data', {}).get('balance', 0))


async def create_qris_deposit(amount: int) -> dict:
    """Creates a QRIS deposit on RamaShop. Returns the raw response dict:
    {depositId, amount, uniqueCode, totalAmount, fee, qrImage, qrString,
    status, expiredAt}. totalAmount (amount + uniqueCode) is what the
    buyer must actually transfer -- RamaShop matches paid deposits by
    that exact figure, so callers must display totalAmount, not amount.
    """
    if not pakasir_configured():
        raise PaymentGatewayError('RAMASHOP_API_KEY not configured.')

    url = f'{RAMASHOP_BASE}/deposit/create'
    body = {'amount': amount, 'method': 'qris'}
    async with aiohttp.ClientSession() as session:
        async with session.post(url, json=body, headers=_post_headers()) as resp:
            # Read as raw text first instead of resp.json() directly --
            # RamaShop (or an intermediary like Cloudflare/the host's
            # network) can return a non-JSON body (empty, an HTML error
            # page, a plain-text rate-limit message) on error responses,
            # and parsing that straight as JSON crashes with an opaque
            # "Expecting value: line 1 column 1" that hides what the
            # server actually sent. Surfacing the real status+body here
            # makes that failure diagnosable instead of a bare traceback.
            raw = await resp.text()
            try:
                data = json.loads(raw) if raw.strip() else {}
            except json.JSONDecodeError:
                raise PaymentGatewayError(
                    f'RamaShop deposit/create returned a non-JSON response ({resp.status}): {raw[:300]!r}'
                )
            if resp.status != 200 or not data.get('success'):
                raise PaymentGatewayError(f'RamaShop deposit/create failed ({resp.status}): {data}')
            return data.get('data', {})


async def get_deposit_status(deposit_id: str) -> dict | None:
    """Polls RamaShop directly for a deposit's true status. Returns the
    inner data dict ({status, paidAmount, paidAt} once settled, or just
    {status: 'pending'} while waiting), or None if the deposit doesn't
    exist. RamaShop caches this endpoint for ~5s server-side, so callers
    shouldn't poll faster than that.

    status is one of:
      'pending' -- no matching QRIS transfer found yet
      'success' -- a matching transfer was found and verified just now
      'already' -- this deposit was already confirmed on a previous check
    """
    if not pakasir_configured():
        raise PaymentGatewayError('RAMASHOP_API_KEY not configured.')

    url = f'{RAMASHOP_BASE}/deposit/status/{deposit_id}'
    async with aiohttp.ClientSession() as session:
        async with session.get(url, headers=_get_headers()) as resp:
            if resp.status == 404:
                return None
            raw = await resp.text()
            try:
                data = json.loads(raw) if raw.strip() else {}
            except json.JSONDecodeError:
                raise PaymentGatewayError(
                    f'RamaShop deposit/status returned a non-JSON response ({resp.status}): {raw[:300]!r}'
                )
            if resp.status != 200 or not data.get('status'):
                raise PaymentGatewayError(f'RamaShop deposit/status failed ({resp.status}): {data}')
            return data.get('data', {})


async def cancel_transaction(order_id: str, amount: int) -> None:
    """RamaShop's docs don't expose a cancel endpoint -- deposits just
    expire on their own. Kept as a no-op so callers (and any future admin
    tooling) don't need a gateway-specific branch.
    """
    return None


async def create_payment_order(*, guild_id: str, channel_id: str, buyer_id: str,
                                product_id: str, product_name: str, amount: int) -> dict:
    deposit = await create_qris_deposit(amount)
    order_id = f'{channel_id}-{_now_ms()}'

    record = {
        'orderId': order_id,
        'gatewayDepositId': deposit.get('depositId'),
        'guildId': guild_id,
        'channelId': channel_id,
        'buyerId': buyer_id,
        'productId': product_id,
        'productName': product_name,
        # amount is the bare product price; totalAmount is what the buyer
        # must actually transfer (amount + RamaShop's unique code) and is
        # what every embed/message shown to the buyer must display.
        'amount': amount,
        'uniqueCode': deposit.get('uniqueCode'),
        'totalAmount': deposit.get('totalAmount', amount),
        'gateway': 'ramashop',
        'status': 'pending',
        'qrImageUrl': deposit.get('qrImage'),
        'qrString': deposit.get('qrString'),
        'createdAt': _now_ms(),
        'expiredAt': _now_ms() + ORDER_EXPIRY_MS,
    }
    db.collection('paymentOrders').document(order_id).set(record)
    return record


async def get_payment_order(order_id: str) -> dict | None:
    doc = db.collection('paymentOrders').document(order_id).get()
    if not doc.exists:
        return None
    return {'id': doc.id, **doc.to_dict()}


async def find_order_by_gateway_deposit_id(deposit_id: str) -> dict | None:
    query = (
        db.collection('paymentOrders')
        .where('gatewayDepositId', '==', deposit_id)
        .limit(1)
    )
    docs = list(query.stream())
    if not docs:
        return None
    return {'id': docs[0].id, **docs[0].to_dict()}


async def find_pending_order_for_channel(channel_id: str) -> dict | None:
    query = (
        db.collection('paymentOrders')
        .where('channelId', '==', channel_id)
        .where('status', '==', 'pending')
        .limit(1)
    )
    docs = list(query.stream())
    if not docs:
        return None
    return {'id': docs[0].id, **docs[0].to_dict()}


async def find_latest_order_for_channel(channel_id: str) -> dict | None:
    """Like find_pending_order_for_channel but also matches orders already
    marked 'completed'. Used by /product forcecheck so it can still find
    (and re-sync the embed for) an order that got confirmed by another
    path -- e.g. the poller or the button -- moments before forcecheck ran,
    instead of reporting 'no pending payment' just because the status
    field had already moved on.

    Runs two single-field queries instead of one 'in' + order_by query, to
    avoid depending on a composite Firestore index that may not exist.
    """
    candidates = []
    for status in ('pending', 'completed'):
        query = (
            db.collection('paymentOrders')
            .where('channelId', '==', channel_id)
            .where('status', '==', status)
            .limit(5)
        )
        candidates.extend({'id': doc.id, **doc.to_dict()} for doc in query.stream())

    if not candidates:
        return None
    return max(candidates, key=lambda o: o.get('createdAt', 0))


async def find_all_pending_orders() -> list[dict]:
    """Used on bot startup to resume in-memory polling for orders that
    were still 'pending' when the process died/restarted. Firestore is
    the source of truth, so a restart mid-payment never loses the order --
    only the in-memory QRISPaymentView + poll loop need recreating.
    Already-expired orders (past expiredAt) are skipped; the caller should
    mark those 'expired' instead of resuming them.
    """
    query = db.collection('paymentOrders').where('status', '==', 'pending')
    docs = list(query.stream())
    return [{'id': doc.id, **doc.to_dict()} for doc in docs]


async def mark_order_completed(order_id: str):
    db.collection('paymentOrders').document(order_id).set(
        {'status': 'completed', 'completedAt': _now_ms()}, merge=True
    )


async def mark_order_status(order_id: str, status: str):
    db.collection('paymentOrders').document(order_id).set({'status': status}, merge=True)


async def set_order_message(order_id: str, message_id: str):
    """Stores the Discord message ID for the QR-code embed so a stale
    embed can be found and updated later even without the in-memory
    QRISPaymentView -- e.g. after a bot restart, or when payment is
    confirmed via /product forcecheck instead of the button/poller.
    """
    db.collection('paymentOrders').document(order_id).set({'messageId': message_id}, merge=True)


async def confirm_payment(order_id: str) -> dict | None:
    """Double-checks a manual /product buy status poll directly against
    RamaShop before treating a payment as real. Returns the order record
    if it's paid (whether we just confirmed it now, or it was already
    marked 'completed' earlier -- e.g. a previous check delivered the
    product but the bot restarted/lost its in-memory view before it could
    update the embed). Returns None only for orders that are still
    genuinely pending or don't exist.
    """
    order = await get_payment_order(order_id)
    if not order:
        return None

    if order['status'] == 'completed':
        # Already confirmed earlier. Caller (_deliver) is idempotent --
        # give_product_to_user/auto_whitelist_product_for_user use
        # ArrayUnion and are safe to re-run, so this just lets a stale
        # embed/button catch up to what Firestore already knows.
        return order

    if order['status'] != 'pending':
        return None

    deposit_id = order.get('gatewayDepositId')
    if not deposit_id:
        return None

    status_data = await get_deposit_status(deposit_id)
    if not status_data:
        return None

    # 'pending' = no matching transfer found yet. 'success' = just
    # verified. 'already' = a previous check already confirmed this same
    # deposit (can happen if the poller and the button both check within
    # RamaShop's ~5s cache window) -- treat it the same as 'success' since
    # it means the money genuinely arrived, just not on this exact call.
    gw_status = str(status_data.get('status', '')).strip().lower()
    if gw_status not in ('success', 'already'):
        print(f'[confirm_payment] {order_id}: gateway status is {status_data.get("status")!r}, not yet settled.')
        return None

    # RamaShop matches deposits by exact transferred amount, so there is
    # no separate fee-vs-price ambiguity to reconcile here the way there
    # was with the old gateway -- paidAmount should equal our stored
    # totalAmount (price + unique code). Log both for visibility; only
    # reject on an outright underpayment, since that's the one case that
    # can never be legitimate.
    paid_amount = status_data.get('paidAmount')
    expected_total = order.get('totalAmount', order['amount'])
    if paid_amount is not None and int(paid_amount) < int(expected_total):
        raise PaymentGatewayError(
            f"Underpayment on {order_id}: expected at least {expected_total}, got {paid_amount}"
        )
    print(f"[confirm_payment] {order_id}: settled, gateway paidAmount={paid_amount}, order totalAmount={expected_total}")

    await mark_order_completed(order_id)
    order['status'] = 'completed'
    return order
